### PR TITLE
Add Elixir project to insert data from CSV to postgres db. Requires e…

### PR DESCRIPTION
**Pull request by Brightergy-JonathanHockman**
…nv vars to be set for db

### CODE REVIEW

**Comment by Brightergy-SamarAcharya** [comment]
@Brightergy-JonathanHockman awesome. btw, I guess we should get rid of csvs from the repos?

**Comment by Brightergy-JonathanHockman** [comment]
@techgaun good point. I'll delete them.

**Comment by Brightergy-JonathanHockman** [comment]
@techgaun Okay done.

**Comment by Brightergy-SamarAcharya** [comment]
:+1:

**Pull request merged**
